---
deployment:
  tasks:
    - echo "=== DEPLOYMENT DEBUG START ==="
    - echo "Current working directory:"
    - pwd
    - echo "Available files to deploy:"
    - ls -la
    - echo "Target deployment path:"
    - export DEPLOYPATH=/home/sjradmin/dev.skyworldcannabis.com/wp-content/themes/skyworld-wp-child
    - echo $DEPLOYPATH
    - echo "Checking if WordPress directory exists:"
    - ls -la /home/sjradmin/dev.skyworldcannabis.com/wp-content/ || echo "WordPress wp-content not found"
    - echo "Creating deployment directory:"
    - /bin/mkdir -p $DEPLOYPATH
    - echo "Copying files:"
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .[^.]* $DEPLOYPATH 2>/dev/null || true
    - echo "Setting permissions:"
    - /bin/chmod -R 755 $DEPLOYPATH
    - echo "Deployment complete! Files in target directory:"
    - ls -la $DEPLOYPATH/
    - echo "=== DEPLOYMENT DEBUG END ==="