---
deployment:
  tasks:
    # Try multiple possible Softaculous paths
    - export DEVPATH1=/home/sjradmin/public_html/dev/wp-content/themes/skyworld-wp-child
    - export DEVPATH2=/home/sjradmin/public_html/wp-content/themes/skyworld-wp-child  
    - export DEVPATH3=/home/sjradmin/public_html/dev.skyworldcannabis.com/wp-content/themes/skyworld-wp-child
    # Find the correct WordPress installation
    - if [ -d "/home/sjradmin/public_html/dev/wp-content" ]; then export DEPLOYPATH=$DEVPATH1; elif [ -d "/home/sjradmin/public_html/wp-content" ]; then export DEPLOYPATH=$DEVPATH2; else export DEPLOYPATH=$DEVPATH3; fi
    - echo "Deploying to: $DEPLOYPATH"
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/* 2>/dev/null || true
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .[^.]* $DEPLOYPATH 2>/dev/null || true
    - /bin/chmod -R 755 $DEPLOYPATH
    - echo "Professional Cannabis Management System deployed successfully!"
    - echo "STANDALONE THEME: No parent theme needed - activate directly!"
    - ls -la $DEPLOYPATH/