---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sjradmin/public_html/dev/wp-content/themes/skyworld-wp-child
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -R .[^.]* $DEPLOYPATH 2>/dev/null || true